"""
SNS Notification Publisher for Cloud Cost Sentinel.
Sends the HTML cost report as an email via an SNS topic.

The topic ARN is read from the SENTINEL_SNS_TOPIC_ARN environment variable.
If the variable is not set or publishing fails, the error is logged and the
function returns gracefully without raising — the overall scan exit code is
not affected.
"""

import logging
import os

import boto3
from botocore.exceptions import BotoCoreError, ClientError

logger = logging.getLogger(__name__)

_ENV_VAR = "SENTINEL_SNS_TOPIC_ARN"


class SNSPublisher:
    """Publishes the cost report as an email notification via SNS."""

    def __init__(self, region: str):
        self.region = region
        self.topic_arn = os.environ.get(_ENV_VAR, "").strip()
        self._client = boto3.client("sns", region_name=region)

    # ------------------------------------------------------------------ #
    # Public interface
    # ------------------------------------------------------------------ #

    def publish_report(
        self, all_findings: dict, html_report: str, report_url: str | None = None
    ) -> bool:
        """
        Publish a plain-text cost summary to the configured SNS topic.

        SNS email subscriptions cannot render HTML, so the message body is
        plain text. A pre-signed URL to the full HTML report is appended when
        available.

        Args:
            all_findings: The raw findings dict from main.py.
            html_report:  Unused; kept for backward compatibility with callers
                          that already pass the rendered HTML string.
            report_url:   Optional pre-signed URL to the S3 HTML report.

        Returns:
            True if the message was published successfully, False otherwise.
        """
        if not self.topic_arn:
            logger.warning(
                f"Skipping SNS notification: {_ENV_VAR} environment variable is not set."
            )
            return False

        subject = self._build_subject(all_findings)
        message = self._build_plain_text_body(all_findings, report_url)
        _ = html_report  # unused; retained for backward-compatible call sites

        try:
            self._client.publish(
                TopicArn=self.topic_arn,
                Subject=subject,
                Message=message,
            )
            logger.info(f"SNS notification sent → {self.topic_arn}")
            return True
        except (BotoCoreError, ClientError) as e:
            logger.error(f"SNS publish failed: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error publishing SNS notification: {e}")
            return False

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def _build_plain_text_body(self, all_findings: dict, report_url: str | None) -> str:
        """Build a readable plain-text email body from findings."""
        account_id = all_findings.get("account_id", "unknown")
        region = all_findings.get("region", "unknown")
        scan_ts = all_findings.get("scan_timestamp", "unknown")
        total = self._total_savings(all_findings)

        def _cost(scanner: str, field: str) -> float:
            return all_findings.get(scanner, {}).get(field, 0.0)

        def _count(scanner: str, field: str) -> int:
            return all_findings.get(scanner, {}).get(field, 0)

        lines = [
            "Cloud Cost Sentinel — Scan Report",
            "=" * 42,
            f"Account ID : {account_id}",
            f"Region     : {region}",
            f"Scan date  : {scan_ts}",
            "",
            "FINDINGS SUMMARY",
            "-" * 42,
            f"EC2  Idle instances       : {_count('ec2', 'idle_instances_count'):>3}   (${_cost('ec2', 'idle_instances_monthly_cost'):.2f}/mo)",
            f"EBS  Unattached volumes   : {_count('ebs', 'unattached_volumes_count'):>3}   (${_cost('ebs', 'unattached_volumes_monthly_cost'):.2f}/mo)",
            f"EBS  Low I/O volumes      : {_count('ebs', 'low_io_volumes_count'):>3}   (${_cost('ebs', 'low_io_volumes_monthly_cost'):.2f}/mo)",
            f"RDS  Idle instances       : {_count('rds', 'idle_instances_count'):>3}   (${_cost('rds', 'idle_instances_monthly_cost'):.2f}/mo)",
            f"RDS  Old snapshots        : {_count('rds', 'old_snapshots_count'):>3}   (${_cost('rds', 'old_snapshots_monthly_cost'):.2f}/mo)",
            f"S3   Unused buckets       : {_count('s3', 'unused_buckets_count'):>3}   (${_cost('s3', 'unused_buckets_monthly_cost'):.2f}/mo)",
            "-" * 42,
            f"Total potential savings   :       ${total:.2f}/mo",
            "",
        ]

        if report_url:
            lines += [
                "Full HTML report (link valid 7 days):",
                report_url,
                "",
            ]

        lines.append("Generated by Cloud Cost Sentinel")
        return "\n".join(lines)

    def _build_subject(self, all_findings: dict) -> str:
        """
        Build a concise email subject line.
        SNS subjects are capped at 100 characters.
        """
        account_id = all_findings.get("account_id", "unknown")
        total_savings = self._total_savings(all_findings)
        subject = f"Cloud Cost Sentinel | Account {account_id} | ${total_savings:.2f}/mo potential savings"
        return subject[:100]

    @staticmethod
    def _total_savings(all_findings: dict) -> float:
        """Sum up monthly cost estimates across all scanner summaries."""
        keys = [
            ("ec2", "idle_instances_monthly_cost"),
            ("ebs", "unattached_volumes_monthly_cost"),
            ("ebs", "low_io_volumes_monthly_cost"),
            ("rds", "idle_instances_monthly_cost"),
            ("rds", "old_snapshots_monthly_cost"),
            ("s3", "unused_buckets_monthly_cost"),
        ]
        total = 0.0
        for scanner, field in keys:
            total += all_findings.get(scanner, {}).get(field, 0.0)
        return round(total, 2)
